name: linting

on:
  pull_request:
    branches:
      - dev
      - main 
      - release
      
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        runner: [ip-10-0-0-106]

    steps:
      
    - name: Checkout code
      uses: actions/checkout@v2


    - name: Set up Node.js
      uses: actions/setup-node@v2 
      with:
        node-version: 18 
        working-directory: /home/ubuntu/actions-runner/_work/CSC-519-Project/CSC-519-Project/coffee-project
    
    - name: Run ESLint
      run: npx eslint app.js
      working-directory: /home/ubuntu/actions-runner/_work/CSC-519-Project/CSC-519-Project/coffee-project

    - name: Run Jest tests
      run: npm test
      working-directory: /home/ubuntu/actions-runner/_work/CSC-519-Project/CSC-519-Project/coffee-project
